site_name: PreciseSearch Documentation

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - python

  palette:
    scheme: slate
    primary: green
    accent: indigo
  
  features:
    - toc.follow # Automatically scroll to the selected anchor
    - toc.integrate # Automatically integrate the table of contents into the page
    - navigation.top # Show the navigation bar at the top of the page
    - navigation.expand
    - navigation.tabs # Show the navigation bar at the top of the page
    - navigation.tabs.sticky # Make the navigation bar sticky
    - search.suggest # Show search suggestions
    - search.share # Show search share


plugins:
  - privacy # Automatically downloads external files/ assets as part of the build process
  - offline # Make the documentation available offline
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
              show_source: true  # Hide source code
              heading_level: 3
              docstring_style: google  # Use Google-style docstrings
              show_signature: true  # Show function signatures
              show_root_heading: true  # Show module/class headings
              separate_signature: true # Keep function signature separate from docstring
              line_length: 80  # Wrap text at 80 characters for better readability 
              filters: ["!^vectorstackai.objects.index"]  # Hides long path prefixes

nav:
  - Home: index.md
  - How-To Guides: how-to-guides.md
  - Python Client Reference: reference.md
  - Tutorials: tutorials.md
  - Explanation: explanation.md

